version: 2

sources:
  - name: raw
    database: ESPORTS
    schema: RAW
    tables:
      - name: LEAGUES
      - name: TOURNAMENTS
      - name: TEAMS
      - name: MATCHES
      - name: TOURNAMENT_ROSTERS